use_frameworks!

target 'iwinks-ble-core-ios_Example' do
  pod 'iwinks-ble-core-ios', :path => '../'

  target 'iwinks-ble-core-ios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
