use_frameworks!

target 'iwinks-ble-core-ios_Example' do
  pod 'iwinks-ble-core-ios', :path => '../'
  pod 'RZBluetooth/Mock'

  target 'iwinks-ble-core-ios_Tests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'RZBluetooth/Test'
  end
end
